language: python
python:
- 3.8
install: pip install -U tox-travis
sudo: false
script: make test-all
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: __token__
  password:
    secure: C8ErsXJ4+tTJic+IBZ7UDoImQbHt8e3o1mK1vyaqb3Ky+bVqvSzMBbe7Zdh+aCy1legsBL7aEL4F9Io4UbRG/8IMmH4vpNij52hFt5ftb722uif9l+vtzmZJh8KKZ8ghegXW8POdCTFaDprtBgphwXtuhk5Ks3EwCUh3H3F8qgGMiQXCnKrnHfrJxevY8hm2ekINktPGwigozDurMcNUj10JokDRz78eXew/EzaoatWL14u/Vjq1w92/oWiNJQh6uQl7mHpMSG+QnisizpUbWKLsdkUypbNSVf8UcSrrYsmel29tqJEsndlq2kI6efH2vmoeNeOhAlZCEZlOfHOneFe1m2RAav2o1r+JTYgqfcvukBvhg5zwBcTXesN4S1uUMManPQCjz6jWnkSvW/Yp9AO96JWl/3icEF0z6AOt26RPR1ZgyjsHMRZPzeDWeZfow5Eh/yio/Um0c2GzKx7SaZA60dSOJSCndkvcv5AEIja+5FDV7zdReZqbc0dKZDqMDFhILSYykxJQn0yBtfuW+12uBVS60bGD4OKjUJAhSOqjE8IZhiotHN5NDTNCbTRzcOzMEONEscWhBON44uW9Z40xqU4aG6u8fTXQjbu1JGV0vEaKUqr5toTa0Y46p/yZJycgHp0FTY+uW0RP6l/XGuQVYpKyrBQMYiqpPBiQzaI=
  on:
    tags: true
    repo: Harmouch101/pydist2
    python: 3.8
